import {
  StockMarketData,
  AgentResult,
  SynthesisResult,
  EvidenceItem,
  PortfolioHolding,
  WatchlistItem,
  StockSymbol,
  RiskProfile,
} from './types';

export const MOCK_STOCKS: Record<StockSymbol, StockMarketData> = {
  RELIANCE: {
    symbol: 'RELIANCE',
    name: 'Reliance Industries Ltd.',
    price: 2984.50,
    currency: 'INR (₹)',
    changePercent: 1.45,
    changeAmount: 42.60,
    priceMomentum: 'Strong Bullish (+4.2% 5D)',
    volumeAnomaly: '+38% vs 20D Avg',
    sentimentScore: 0.72,
    rsi: 64.2,
    volatility: '18.4% Moderate',
  },
  TCS: {
    symbol: 'TCS',
    name: 'Tata Consultancy Services',
    price: 4310.20,
    currency: 'INR (₹)',
    changePercent: 0.68,
    changeAmount: 29.10,
    priceMomentum: 'Moderate Bullish (+1.8% 5D)',
    volumeAnomaly: '+12% vs 20D Avg',
    sentimentScore: 0.58,
    rsi: 58.6,
    volatility: '14.2% Low',
  },
  INFOSYS: {
    symbol: 'INFOSYS',
    name: 'Infosys Limited',
    price: 1895.00,
    currency: 'INR (₹)',
    changePercent: -0.85,
    changeAmount: -16.20,
    priceMomentum: 'Slight Bearish (-1.2% 5D)',
    volumeAnomaly: '-8% vs 20D Avg',
    sentimentScore: 0.35,
    rsi: 46.1,
    volatility: '19.8% Moderate',
  },
  HDFCBANK: {
    symbol: 'HDFCBANK',
    name: 'HDFC Bank Ltd.',
    price: 1642.75,
    currency: 'INR (₹)',
    changePercent: 2.10,
    changeAmount: 33.80,
    priceMomentum: 'Bullish Breakout (+5.1% 5D)',
    volumeAnomaly: '+54% vs 20D Avg',
    sentimentScore: 0.81,
    rsi: 68.4,
    volatility: '16.5% Moderate',
  },
  TATAMOTORS: {
    symbol: 'TATAMOTORS',
    name: 'Tata Motors Ltd.',
    price: 978.30,
    currency: 'INR (₹)',
    changePercent: -1.40,
    changeAmount: -13.90,
    priceMomentum: 'Pullback (-2.4% 5D)',
    volumeAnomaly: '+22% vs 20D Avg',
    sentimentScore: 0.48,
    rsi: 42.8,
    volatility: '24.1% High',
  },
};

export const MOCK_AGENTS: Record<string, Omit<AgentResult, 'status'>> = {
  technical: {
    id: 'technical',
    name: 'Technical Agent',
    role: 'Quantitative & Technical Analysis',
    signal: 'BULLISH',
    confidence: 86,
    reasoning: 'RSI at 64.2 with MACD bullish crossover on daily chart. 20-day EMA trading comfortably above 50-day EMA with expanding Bollinger bands.',
    latencyMs: 420,
    keyFactors: ['MACD Golden Cross', 'RSI 64.2 Bullish Zone', '20D EMA > 50D EMA'],
  },
  sentiment: {
    id: 'sentiment',
    name: 'Sentiment Agent',
    role: 'NLP Market & Media Intelligence',
    signal: 'BULLISH',
    confidence: 81,
    reasoning: 'Scanned 142 recent financial articles & retail sentiment feeds. Aggregate sentiment index stands at +0.72 with positive quarterly outlook consensus.',
    latencyMs: 780,
    keyFactors: ['+0.72 Net Sentiment Index', 'Strong institutional media tone', 'Retail buzz high'],
  },
  fundamental: {
    id: 'fundamental',
    name: 'Fundamental Agent',
    role: 'RAG Filing & Financial Intelligence',
    signal: 'CAUTIOUS',
    confidence: 72,
    reasoning: 'Q1 revenue grew 11.5% YoY led by Telecom & Retail, but O2C refining margins faced a 140 bps contraction. Net Debt-to-EBITDA remains healthy at 1.4x.',
    latencyMs: 1150,
    keyFactors: ['Telecom & Retail ARPU Expansion (+18%)', 'O2C Refining Margin Contraction (-140 bps)', 'Net Debt/EBITDA at 1.4x'],
  },
};

export const MOCK_SYNTHESIS: Record<RiskProfile, SynthesisResult> = {
  Conservative: {
    recommendation: 'HOLD',
    confidence: 78,
    reasons: [
      'Strong price momentum (+4.2% over 5D)',
      'Above-average trading volume (+38% anomaly)',
      'Positive NLP sentiment score (+0.72)',
      'Fundamental refining margin pressure (-140 bps)',
    ],
    riskAdjustment: 'Conservative profile limits exposure due to elevated volatility (18.4%) and refining margin pressure.',
    isDegraded: false,
    overallSignal: 'BULLISH',
  },
  Aggressive: {
    recommendation: 'BUY',
    confidence: 84,
    reasons: [
      'Strong price momentum (+4.2% over 5D)',
      'Above-average trading volume (+38% anomaly)',
      'Positive NLP sentiment score (+0.72)',
      'High growth trajectory in Retail & Digital verticals',
    ],
    riskAdjustment: 'Higher risk tolerance allows greater upside exposure, capitalizing on momentum despite short-term margin fluctuations.',
    isDegraded: false,
    overallSignal: 'BULLISH',
  },
};

export const DEGRADED_SYNTHESIS: SynthesisResult = {
  recommendation: 'INSUFFICIENT EVIDENCE',
  confidence: 0,
  reasons: [
    'Required fundamental evidence and SEBI filings are currently unavailable',
    'System risk engine enforces hard refusal when RAG agent data pipeline degrades',
  ],
  riskAdjustment: 'The system will not generate an unsupported recommendation because required fundamental evidence is unavailable.',
  isDegraded: true,
  overallSignal: 'UNAVAILABLE',
};

export const MOCK_EVIDENCE: EvidenceItem[] = [
  {
    id: 'ev-1',
    title: 'Reliance Industries Q1 FY25 Earnings Statement & Segment Breakdown',
    source: 'SEBI Official Quarterly Filing (Jul 2024)',
    excerpt: 'Gross Revenue grew 11.5% YoY to ₹2,57,823 crore. Jio Infocomm EBITDA increased 14.2% YoY with ARPU expanding to ₹181.7. O2C EBITDA dropped 14.3% YoY owing to lower fuel cracks and global refining margin normalization.',
    agentId: 'fundamental',
    agentName: 'Fundamental Agent',
    date: '2024-07-20',
    confidenceContribution: 45,
  },
  {
    id: 'ev-2',
    title: 'Annual Capital Allocation & New Energy Giga-Factory Roadmap',
    source: 'RIL Annual General Meeting Report 2024',
    excerpt: 'Phased commissioning of the 20 GW Solar PV giga-factory at Dhirubhai Ambani Green Energy Complex commences H2 FY25. Balance sheet net leverage maintained below 1.5x EBITDA.',
    agentId: 'fundamental',
    agentName: 'Fundamental Agent',
    date: '2024-08-29',
    confidenceContribution: 35,
  },
  {
    id: 'ev-3',
    title: 'Global Commodity & Refining Margin Consensus Report',
    source: 'S&P Global Energy Benchmark Insights',
    excerpt: 'Singapore complex refining margins averaged $4.8/bbl in Q1 FY25 compared to $6.7/bbl in Q4 FY24, reflecting global inventory rebuilds and softened middle distillate demand.',
    agentId: 'fundamental',
    agentName: 'Fundamental Agent',
    date: '2024-07-15',
    confidenceContribution: 20,
  },
];

export const MOCK_PORTFOLIO: PortfolioHolding[] = [
  {
    symbol: 'RELIANCE',
    name: 'Reliance Industries Ltd.',
    quantity: 150,
    avgPrice: 2450.00,
    currentPrice: 2984.50,
    currentExposure: 447675.00,
    returnPercent: 21.82,
    concentrationScore: 34.2,
  },
  {
    symbol: 'TCS',
    name: 'Tata Consultancy Services',
    quantity: 60,
    avgPrice: 3820.00,
    currentPrice: 4310.20,
    currentExposure: 258612.00,
    returnPercent: 12.83,
    concentrationScore: 19.7,
  },
  {
    symbol: 'HDFCBANK',
    name: 'HDFC Bank Ltd.',
    quantity: 120,
    avgPrice: 1510.00,
    currentPrice: 1642.75,
    currentExposure: 197130.00,
    returnPercent: 8.79,
    concentrationScore: 15.0,
  },
];

export const MOCK_WATCHLIST: WatchlistItem[] = [
  { symbol: 'TCS', name: 'Tata Consultancy', price: 4310.20, changePercent: 0.68, signal: 'BULLISH' },
  { symbol: 'INFOSYS', name: 'Infosys Ltd', price: 1895.00, changePercent: -0.85, signal: 'NEUTRAL' },
  { symbol: 'HDFCBANK', name: 'HDFC Bank', price: 1642.75, changePercent: 2.10, signal: 'BULLISH' },
  { symbol: 'TATAMOTORS', name: 'Tata Motors', price: 978.30, changePercent: -1.40, signal: 'CAUTIOUS' },
];

